---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: refunc-system
  labels:
    refunc.io/res: gateway
    refunc.io/name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      refunc.io/res: gateway
      refunc.io/name: mcp-server
  template:
    metadata:
      labels:
        refunc.io/res: gateway
        refunc.io/name: mcp-server
    spec:
      serviceAccount: refunc
      containers:
        - name: api
          image: refunc/mcp-server
          imagePullPolicy: IfNotPresent
          command:
            - mcp-server
          env:
            - name: REFUNC_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REFUNC_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_ENDPOINT
              value: "nats.refunc-system:4222"
            - name: ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: refunc
                  key: access-token