---
kind: Service
apiVersion: v1
metadata:
  name: mcp-server
  namespace: refunc-system
  labels:
    refunc.io/res: gateway
    refunc.io/name: mcp-server
spec:
  selector:
    refunc.io/res: gateway
    refunc.io/name: mcp-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000