#!/bin/bash

source ./scripts/common

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
#GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [[ -z "$DIRTY" && -n "$COMMIT" ]]; then
    VERSION=$COMMIT
    export MCP_SERVER_VERSION=${VERSION}
else
    _DEPS_VERSION=$(
        echo \
        $(get_version $(find pkg -type f -name '*.go'))
    )
    export MCP_SERVER_VERSION=$(echo $(get_version $(find pkg cmd -type f -name '*.go') package/Dockerfile go.mod go.sum) | my_sha1sum | cut -c 1-8)${DIRTY}
fi

IMAGE_REPO=${IMAGE_REPO:-refunc}

export REGISTRY_PREFIX="${IMAGE_REPO}/${IMAGE_PREFIX}"

export MCP_SERVER_IMAGE="${REGISTRY_PREFIX}mcp-server:${MCP_SERVER_VERSION}"
